# Generated by Django 5.0.5 on 2024-06-25 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0011_direccion_pedido_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, default='producto/default.jpg', null=True, upload_to='producto'),
        ),
    ]
