# Generated by Django 5.0.5 on 2024-06-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0013_marca_alter_detallepedido_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, default='media/producto/default.jpg', null=True, upload_to='producto'),
        ),
    ]
