# Generated by Django 5.0.5 on 2024-07-01 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0014_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, default='/producto/default.jpg', null=True, upload_to='producto'),
        ),
    ]
