# Generated by Django 5.0.5 on 2024-07-01 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0016_alter_detallepedido_user_alter_direccion_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='../media/default.jpg', upload_to='producto/'),
        ),
    ]
