# Generated by Django 5.0.5 on 2024-07-02 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0020_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='C:/Users/nicol/Desktop/Integracionnde plataformas/Pagina web/FERREMAS/media/default.jpg', upload_to='producto'),
        ),
    ]
