# Generated by Django 5.0.5 on 2024-07-08 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0021_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[(0, 'En preparación'), (1, 'En camino'), (2, 'Entregado')], default=0, max_length=20),
        ),
    ]
