# Generated by Django 5.0.5 on 2024-07-08 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0022_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='direccion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='direccion', to='producto.direccion'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.IntegerField(choices=[(0, 'En preparación'), (1, 'En camino'), (2, 'Entregado')], default=0),
        ),
    ]
