# Generated by Django 5.0.5 on 2025-05-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0023_alter_pedido_direccion_alter_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='numero',
            field=models.CharField(max_length=50),
        ),
    ]
